language: python

python:
    - "3.6"

services: mongodb

sudo: false

env:
    - TOX_ENV=dj2-py36-me019
    - TOX_ENV=dj30-py36-me019

matrix:
    fast_finish: true

install:
    - pip install tox virtualenv djangorestframework codecov

script:
    - tox -e $TOX_ENV

after_success:
    - codecov -e TOX_ENV

notifications:
    email: false
