os: linux
dist: xenial

language: python

jobs:
  include:
    # Python version is just for the look on travis.
    # Test the full python/django matrix with postgresql
    - python: 3.6
      env: TOXENV=py36-django111-postgresql
    - python: 3.7
      env: TOXENV=py37-django111-postgresql
    - python: 3.6
      env: TOXENV=py36-django20-postgresql
    - python: 3.7
      env: TOXENV=py37-django20-postgresql
    - python: 3.6
      env: TOXENV=py36-django21-postgresql
    - python: 3.7
      env: TOXENV=py37-django21-postgresql
    - python: 3.6
      env: TOXENV=py36-django22-postgresql
    - python: 3.7
      env: TOXENV=py37-django22-postgresql
    - python: 3.8
      env: TOXENV=py38-django22-postgresql
    - python: 3.9
      env: TOXENV=py39-django22-postgresql
    - python: 3.6
      env: TOXENV=py36-django30-postgresql
    - python: 3.7
      env: TOXENV=py37-django30-postgresql
    - python: 3.8
      env: TOXENV=py38-django30-postgresql
    - python: 3.9
      env: TOXENV=py39-django30-postgresql
    - python: 3.6
      env: TOXENV=py36-django31-postgresql
    - python: 3.7
      env: TOXENV=py37-django31-postgresql
    - python: 3.8
      env: TOXENV=py38-django31-postgresql
    - python: 3.9
      env: TOXENV=py39-django31-postgresql
    # Test against sqlite once for each major django version.
    - python: 3.6
      env: TOXENV=py36-django111-sqlite
    - python: 3.7
      env: TOXENV=py37-django22-sqlite
    - python: 3.8
      env: TOXENV=py38-django31-sqlite
    # Check flake8 once.
    - python: 3.6
      env: TOXENV=py36-flake8

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database dirtyfields_test;' -U postgres

script:
  - tox

install:
  - pip install tox
  - pip install coveralls

after_success:
  # only upload coverage report to coveralls from one job.
  - if test "$TOXENV" = "py36-django111-postgresql"; then coveralls; fi

deploy:
  edge: true  # opt in to dpl v2
  provider: pypi
  # We use the __token__ special key to indicate that we use Pypi API token, instead of the
  # username/password combinaison
  username: "__token__"
  # No need to provide the password anymore. It has been set as an PYPI_PASSWORD environment variable
  # on travis-ci.org web interface, and is picked automatically in this deploy stage for pypi.
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
    all_branches: true
    repo: romgar/django-dirtyfields
