sudo: false
language: python
python:
  - 3.8
  - 3.7
  - 3.6
cache: pip
env:
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning,ignore::ResourceWarning
  matrix:
    - DJANGO='>=3.0,<3.1'
    - DJANGO='>=2.2,<3.0'
    - DJANGO='>=2.1,<2.2'
    - DJANGO='>=2.0,<2.1'
    - DJANGO='>=1.11,<1.12'
matrix:
  fast_finish: true
  exclude:
    - python: 3.8
      env: DJANGO='>=1.11,<1.12'
    - python: 3.7
      env: DJANGO='>=1.11,<1.12'
addons:
  apt:
    packages:
      - libmysqlclient-dev
services:
  - postgresql
  - mysql
install:
  - pip install flake8 coverage django$DJANGO psycopg2 mysqlclient -e .
before_script:
  - mysql -e 'create database test_project'
  - psql -c 'create database test_project;' -U postgres;
script:
  - flake8
  - coverage run -a tests/runtests.py
  - coverage run -a tests/runtests.py -d psql
  - coverage run -a tests/runtests.py -d mysql
after_success:
  - coverage report
deploy:
  provider: pypi
  user: etianen
  password:
    secure: rzaq3pbJz25SVXyR/fn+gLaYxu0LqCEE+wcesg8pjA8cLLvFdLvXi0ZjmixxVl2u4HlndZrUgwTrRGVIQR1TOL0jGRYOUCJDzAaZqJkg+Qykz89iKSnentyOpNJe6fRAHsqFxBESYZjG8JEZvtRv+JIZLY+QR+KCA1xaeu4Afpw=
  on:
    tags: true
    condition: $DJANGO = '>=3.0,<3.1'
    python: 3.8
    repo: etianen/django-watson
notifications:
  email: false
