language: python
cache: pip
python:
- '3.5'
- '3.6'
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
- pip install pipenv --upgrade
- pipenv sync --dev
script:
- pipenv run -- pytest --cov=hendrix -v test
after_success:
  - codecov
