language: python
python:
- '3.5'

env:
- MOZ_HEADLESS=1
addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - python setup.py install
  - pip install -r requirements/heroku_requirements.txt

script:
  - pytest --cov=koalixcrm --cov-branch --cov-report xml --cov-report term -m "not version_increase"
  - python-codacy-coverage -r coverage.xml
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pytest -m version_increase; fi

# Deployment
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY

  app: koalix-crm
  on:
    repo: scaphilo/koalixcrm
  run:
  - "python manage.py collectstatic --settings=projectsettings.settings.heroku_settings --noinput"
  - "python manage.py migrate --settings=projectsettings.settings.heroku_settings"
