language: python

cache: pip

python:
  - "3.6"
  - "3.7"

services:
  - mysql

addons:
  postgresql: "9.5"

branches:
  only:
    - master

env:
  matrix:
   - DJANGO="django>=2.2,<2.3" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test'
   - DJANGO="django>=2.2,<2.3" DATABASE_URL='postgres://postgres@127.0.0.1/freeradius_test'
   - DJANGO="django>=2.1,<2.2" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test'
   - DJANGO="django>=2.1,<2.2" DATABASE_URL='postgres://postgres@127.0.0.1/freeradius_test'
   - DJANGO="django>=3.0,<3.1" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test'
   - DJANGO="django>=3.0,<3.1" DATABASE_URL='postgres://postgres@127.0.0.1/freeradius_test'
   - SAMPLE_APP=1 DJANGO="django>=2.1,<2.2" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test'
   - SAMPLE_APP=1 DJANGO="django>=3.0,<3.1" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test'
   - DJANGO="django>=2.0,<2.1" DATABASE_URL='sqlite:///django-freeradius.db'
   - DJANGO="django>=3.0,<3.1" DATABASE_URL='sqlite:///django-freeradius.db'

before_install:
  - pip install -U pip wheel
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint
  - jslint ./django_freeradius/static/django-freeradius/js/*.js

install:
  - pip install $DJANGO
  - python setup.py -q develop

before_script:
  - if [ "$DATABASE_URL" == 'postgres://postgres@127.0.0.1/freeradius_test' ]; then psql -c "CREATE DATABASE freeradius_test;" -U postgres; fi
  - mysql -e "CREATE DATABASE IF NOT EXISTS freeradius_test;"
  - >
    openwisp-utils-qa-checks --migration-path "./django_freeradius/migrations ./tests/sample_radius/migrations"
    --skip-checkmakemigrations 
  - |
    if [[ $SAMPLE_APP != "1" ]]; then
      openwisp-utils-qa-checks \
        --skip-isort \
        --skip-flake8 \
        --skip-checkmigrations \
        --skip-checkendline \
        --skip-checkcommit \
        --migration-module django_freeradius
    fi
  - ./runsphinx-build
  - ./tests/manage.py migrate

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=django_freeradius runtests.py

after_success:
  coveralls
