codecov:
  branch: master
  bot: "youknowone"

coverage:
  precision: 2
  round: nearest
  range: "10...90"

  status:
    project: true
    patch: true
    changes: true

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
