language: python
python:
  - "3.4"
  - "3.5"
# django 1.4.0 doesn't have six. Only newest version have this module.
env:
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.11
  - DJANGO=django==1.8.7
  - DJANGO=django==1.9
# Django 1.4 doesn't support Python 3
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=django==1.6.11
    - python: "3.5"
      env: DJANGO=django==1.7.11
    - python: "3.5"
      env: DJANGO=django==1.8.7
install:
  - pip install $DJANGO
  - "pip install -r requirements.txt"
script: python tests.py
